name: CI Tests
on:
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install -g pnpm@8 && pnpm install --ignore-scripts
      
      - name: Run unit tests
        shell: bash
        run: pnpm test
        